# Generated by Django 5.0.2 on 2024-03-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=11, verbose_name="手机号")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="价格"
                    ),
                ),
                (
                    "leval",
                    models.SmallIntegerField(
                        choices=[(1, "高级"), (2, "普通")], default=2, verbose_name="等级"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "空闲"), (2, "售出")], default=1, verbose_name="状态"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(max_length=32, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="depart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.department",
                verbose_name="部门",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="passwd",
            field=models.CharField(max_length=64, verbose_name="密码111"),
        ),
    ]
